version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      QDRANT_URL: http://qdrant:6333
    depends_on:
      - qdrant

volumes:
  qdrant_storage:
